In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/My Drive/game_knn.csv')
df

Name  Age Gender     Sport
0    A   32      M  Football
1    B   40      M   Neither
2    C   16      F   Cricket
3    D   34      F   Cricket
4    E   55      M   Neither
5    F   40      M   Cricket
6    G   20      F   Neither
7    H   15      M   Cricket
8    I   55      F  Football
9    J   15      M  Football

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
label = le.fit_transform(df['Gender'])
label

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
df

Name  Age Gender     Sport
0    A   32      M  Football
1    B   40      M   Neither
2    C   16      F   Cricket
3    D   34      F   Cricket
4    E   55      M   Neither
5    F   40      M   Cricket
6    G   20      F   Neither
7    H   15      M   Cricket
8    I   55      F  Football
9    J   15      M  Football

In [ ]:
df=df.drop('Gender', axis = 'columns')
df

Name  Age     Sport
0    A   32  Football
1    B   40   Neither
2    C   16   Cricket
3    D   34   Cricket
4    E   55   Neither
5    F   40   Cricket
6    G   20   Neither
7    H   15   Cricket
8    I   55  Football
9    J   15  Football

In [ ]:
df.insert(2,'Gender',label)
df

Name  Age  Gender     Sport
0    A   32       1  Football
1    B   40       1   Neither
2    C   16       0   Cricket
3    D   34       0   Cricket
4    E   55       1   Neither
5    F   40       1   Cricket
6    G   20       0   Neither
7    H   15       1   Cricket
8    I   55       0  Football
9    J   15       1  Football

In [ ]:
x = df.iloc[:,1:3].values
x

array([[32,  1],
       [40,  1],
       [16,  0],
       [34,  0],
       [55,  1],
       [40,  1],
       [20,  0],
       [15,  1],
       [55,  0],
       [15,  1]])

In [ ]:
y = df.iloc[:,3]
y

0    Football
1     Neither
2     Cricket
3     Cricket
4     Neither
5     Cricket
6     Neither
7     Cricket
8    Football
9    Football
Name: Sport, dtype: object

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
classifier = KNeighborsClassifier(metric = 'euclidean' , n_neighbors = 3)

In [28]:
classifier.fit(x , y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [29]:
pred_y=classifier.predict(x)
pred_y

array(['Cricket', 'Cricket', 'Cricket', 'Cricket', 'Neither', 'Cricket',
       'Cricket', 'Cricket', 'Neither', 'Cricket'], dtype=object)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [31]:
cm = confusion_matrix(y,pred_y)
cm

array([[4, 0, 0],
       [2, 0, 1],
       [2, 0, 1]])

In [47]:
acc = accuracy_score(y,pred_y)*100

In [48]:
acc

50.0

In [50]:
x_new = np.array([[18,1]])
prediction = classifier.predict(x_new)
prediction

array(['Cricket'], dtype=object)

In [ ]:
import matplotlib.pyplot as plt
