In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df=pd.read_csv('/content/drive/My Drive/tissue.csv')
df

x1  x2     y
0   7   7   bad
1   7   4   bad
2   3   4  good
3   1   4  good

In [ ]:
x=df.iloc[:,0:2].values
x

array([[7, 7],
       [7, 4],
       [3, 4],
       [1, 4]])

In [ ]:
y=df.iloc[:,2].values
y

array(['bad', 'bad', 'good', 'good'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder


In [ ]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 1, 1])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')

In [ ]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
pred_y = classifier.predict(x)
pred_y

array([0, 0, 1, 1])

In [ ]:
y

array([0, 0, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
cm = confusion_matrix(y,pred_y)
cm

array([[2, 0],
       [0, 2]])

In [ ]:
acc = accuracy_score(y,pred_y)*100
acc

100.0

In [ ]:
x_new = np.array([[1,5]])
x_new

array([[1, 5]])

In [ ]:
prediction = classifier.predict(x_new)
prediction

array([1])

In [ ]:
df=pd.read_csv('/content/drive/My Drive/game_knn.csv')
df

Name  Age Gender     Sport
0    A   32      M  Football
1    B   40      M   Neither
2    C   16      F   Cricket
3    D   34      F   Cricket
4    E   55      M   Neither
5    F   40      M   Cricket
6    G   20      F   Neither
7    H   15      M   Cricket
8    I   55      F  Football
9    J   15      M  Football

In [ ]:
le = LabelEncoder()
label = le.fit_transform(df['Gender'])
label


array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
df = df.drop('Gender',axis= 1)
df

Name  Age     Sport
0    A   32  Football
1    B   40   Neither
2    C   16   Cricket
3    D   34   Cricket
4    E   55   Neither
5    F   40   Cricket
6    G   20   Neither
7    H   15   Cricket
8    I   55  Football
9    J   15  Football

In [ ]:
df.insert(2,column = 'Gender', value = label)
df

ValueError: ignored

In [ ]:
 ValueError(f"cannot insert {item}, already exists")
 

NameError: ignored